FROM squidfunk/mkdocs-material

COPY requirements.txt .
RUN pip install -r requirements.txt \
    && pip install mkdocs-static-i18n \
    && pip install mkdocs

WORKDIR /docs

EXPOSE 8000

ENTRYPOINT ["mkdocs"]
CMD ["serve", "--dev-addr=0.0.0.0:8000"]
