# --- Stage 1: Build ---
FROM golang:1.24-alpine AS build
WORKDIR /app

# Кэширование модулей
COPY go.mod go.sum ./
RUN go mod download

# Копируем весь код и собираем статический бинарь
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -trimpath -ldflags="-s -w" -o server ./cmd/server

# --- Stage 2: Minimal runtime ---
FROM gcr.io/distroless/static:nonroot
WORKDIR /srv

# Копирование бинарника из билдера
COPY --from=build /app/server /srv/server

# Открытие порта
EXPOSE 8080

# Переменные окружения
ENV ADDR=":8080"

# Запуск от не рута
USER nonroot:nonroot

# Запуск приложения
ENTRYPOINT ["/srv/server"]